security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Project\FilmsBundle\Entity\Client: bcrypt
    providers:
        main:
            entity: { class: Project\FilmsBundle\Entity\Client, property: username }
    firewalls:
      main:
        pattern: /.*
        form_login:
          login_path: /login
          check_path: /login_check
          default_target_path: /
        logout:
          path: /logout
          target: /
        security: true
        anonymous: true

        #   target: /book
        # security: true
        # anonymous: true
          # security: true
          # anonymous: true
